<div class="row">
    <br/>
    <h2 class="text-center">Cadastro de Categorias</h2>
    <hr>
</div>
<form method="post" action="Request.php?class=app\controller\CategoriaCtr&method=run">
    <input type="hidden" name="id" id="id" value="<?= $this->model->getId() ?>">
    <div class="row">
        <div class="small-12 medium-12 large-12 columns">
            <label>
                Nome da Categoria:
                <input type="text" name="nome" id="nome" value="<?= $this->model->getNome() ?>" maxlength="100" required="required">
            </label>
        </div>        
    </div>
    <div class="row">
        <div class="small-12 medium-6 large-4 columns">
            Operação: <br/>
            <input required="required" id="c" type="radio" <?php if ($this->model->getOperacao() == "C") { ?> checked="checked" <?php } ?> name="operacao" value="C"><label for="c">Crédito</label>
            <input required="required" id="d" type="radio" <?php if ($this->model->getOperacao() == "D") { ?> checked="checked" <?php } ?> name="operacao" value="D"><label for="d">Débito</label>
        </div>
        <div class="small-12 medium-6 large-8 columns">
            <label for="valortotal">Valor total:</label>
            <div class="row collapse prefix-radius">
                <div class="small-3 columns">
                    <span class="prefix">R$</span>
                </div>
                <div class="small-9 columns">
                    <input type="number" name="valortotal" id="valorbase" value="<?= $this->model->getTotal() ?>" id="valor" readonly="readonly">
                </div>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="small-12 medium-4 large-4 columns">
            <input type="submit" class="button expand radius success" name="comando" value="Salvar">
        </div>        
        <div class="small-12 medium-4 large-4 columns">
            <input type="submit" class="button expand radius" name="comando" value="Novo">
        </div>
        <div class="small-12 medium-4 large-4 columns">
            <input type="submit" class="button expand radius alert" name="Excluir" value="Excluir">
        </div>
    </div>
    <br/>
    <div class="row">
        <hr/>
    </div>
    <br/>
    <div class="row">
        <div class="small-12 medium-4 large-4 medium-centered large-centered columns">
            <a class="button expand radius secondary" href="Request.php?class=app\controller\CategoriaCtr&method=showList">Listagem</a>
        </div>
    </div>
    <br>
</form>
