<div class="row">
    <h2 class="text-center">Cadastro de Categorias</h2>
</div>
<hr>
<form method="post" action="Request.php?class=app\controller\CategoriaCtr&method=run">
    <input type="hidden" name="id" id="id" value="<?= $this->model->getId() ?>">
    <div class="row">
        <div class="small-">
            <label>
                Nome da Categoria:
                <input type="text" name="nome" id="nome" value="<?= $this->model->getNome() ?>" maxlength="50" required="required">
            </label>
        </div>
    </div>
    <div class="row">
        <div class="small-12 medium-4 large-4 columns">
            <input type="submit" class="button expand round" name="comando" value="Novo">
        </div>
        <div class="small-12 medium-4 large-4 columns">
            <input type="submit" class="button expand round success" name="comando" value="Salvar">
        </div>
        <div class="small-12 medium-4 large-4 columns">
            <input type="submit" class="button expand round alert" name="Excluir" value="Excluir">
        </div>
    </div>
    <br/>
    <hr/>
    <br/>
    <div class="row">
        <div class="small-12 medium-4 large-4 medium-centered large-centered columns">
            <a class="button tiny expand round" href="Request.php?class=app\controller\CategoriaCtr&method=showList">Listagem</a>
        </div>
    </div>
    <br>
</form>
