<div class="row">
    <br/>
    <h2 class="text-center">Lista de Categorias</h2>
    <hr>
</div>
<form method="post" action="#">
    <div class="row">
        <h5 class="text-left">Parâmetros para pesquisa</h5>
    </div>
    <div class="row">
        <div class="small-12 medium-7 large-8 columns">
            <label>Nome:
                <input type="text" name="nome" id="nome">
            </label>
        </div>
        <div class="small-12 medium-5 large-4 columns">
            Operação: <br/>
            <input id="c" type="radio" name="operacao" value="C"><label for="c">Crédito</label>
            <input id="d" type="radio" name="operacao" value="D"><label for="d">Débito</label>
            <input id="t" type="radio" name="operacao" value="todas" checked><label for="t">Todas</label>
        </div>
    </div>
    <div class="row">
        <div class="small-8 small-centered medium-6 medium-centered large-5 large-centered columns">
            <button type="button" onclick="retornarCategoriasJson()" class="button tiny success radius" name="listar">Listar</button>
            <input type="reset" class="button tiny secondary radius" value="Limpar">
            <a class="button tiny radius" href="Request.php?class=app\controller\CategoriaCtr&method=showView">Cadastrar</a>
        </div>
    </div> 
</form>
<br/>
<div class="row">
    <hr/>
    <h5 class="text-left">Listagem</h5>
    <br/>
    <div class="small-12 medium-12 large-12 columns">
        <table class="show-for-medium-up medium-12 large-12 columns">
            <thead>
                <tr>
                    <th>#</th>
                    <th>Nome</th>
                    <th>Operação</th>
                    <th>Total</th>
                    <th>Ver categoria</th>
                </tr>
            </thead>
            <tbody id="tabelaGrande">
            </tbody>
        </table>
        <div class="show-for-small-only small-12">
            <table class="small-12 columns">
                <thead>
                    <tr>
                        <th>#</th>
                        <th>Nome</th>
                        <th>Ver categoria</th>
                    </tr>
                </thead>
                <tbody id="tabelaPequena">
                </tbody>
            </table>
        </div>
    </div>
</div>