<div class="row">
    <br/>
    <h2 class="text-center">Cadastro de Categorias</h2>
    <hr>
</div>
<form method="post" id="formCadastro" action="Request.php?class=app\controller\CategoriaCtr&method=run">
    <input type="hidden" name="id" id="id" value="<?= $this->model->getId() ?>">
    <div class="row">
        <div class="small-12 medium-12 large-12 columns">
            <label>
                Nome da Categoria:
                <input type="text" name="nome" id="nome" value="<?= $this->model->getNome() ?>" maxlength="100" required="required">
            </label>
        </div>        
    </div>
    <div class="row">
        <div class="small-12 medium-4 large-3 columns">
            Operação: <br/>
            <input required="required" id="c" type="radio" <?php if ($this->model->getOperacao() == "C" || ($this->model->getOperacao() != "C" && $this->model->getOperacao() != "C")) { ?> checked="checked" <?php } ?> name="operacao" value="C"><label for="c">Crédito</label>
            <input required="required" id="d" type="radio" <?php if ($this->model->getOperacao() == "D") { ?> checked="checked" <?php } ?> name="operacao" value="D"><label for="d">Débito</label>
        </div>
        <div class="small-12 medium-8 large-9 columns">
            <label for="valortotal">Valor total:</label>
            <div class="row collapse prefix-radius">
                <div class="small-3 columns">
                    <span class="prefix">R$</span>
                </div>
                <div class="small-9 columns">
                    <input type="number" name="valortotal" step="0.01" id="valorbase" value="<?php if ($this->model->getTotal() == "") { ?>0.00<?php
                    } else {
                        echo $this->model->getTotal();
                    }
                    ?>" id="valor" readonly="readonly">
                </div>
            </div>
        </div>
    </div>
    <div class="row">
        <?php
        $medium = "medium-6";
        $large = "large-6";
        if ($this->model->getId() != null && $this->model->getId() != 0) {
            $medium = "medium-4";
            $large = "large-4";
        }
        ?>
        <div class="small-12 <?= $medium ?> <?= $large ?> columns">
            <input type="submit" onclick="return salvarAjax('Request.php?class=app\\controller\\CategoriaCtr&method=run', 'salvar')" class="button expand radius success" name="comando" value="Salvar">
        </div>        
        <div class="small-12 <?= $medium ?> <?= $large ?> columns">
            <input type="submit" class="button expand radius info" name="comando" value="Novo">
        </div>
        <?php if ($this->model->getId() != null && $this->model->getId() != 0) { ?>
            <div class="small-12 <?= $medium ?> <?= $large ?> columns">
                <input type="submit" onclick="return perguntaExcluir('Request.php?class=app\\controller\\CategoriaCtr&method=run', 'excluir')" class="button expand radius alert" name="comando" value="Excluir">
            </div>
        <?php } ?>
    </div>
    <br/>
    <div class="row">
        <hr/>
    </div>
    <br/>
    <div class="row">
        <div class="small-12 medium-4 large-4 medium-centered large-centered columns">
            <a class="button expand radius secondary" href="Request.php?class=app\controller\CategoriaCtr&method=showList">Listagem</a>
        </div>
    </div>
    <br>
</form>
<div name="div" id='myModal' class='reveal-modal' data-reveal aria-labelledby='modalTitle' aria-hidden='false' role=dialog'></div>
