<div class="row">
    <br/>
    <h2 class="text-center">Cadastro de Itens</h2>
    <hr>
</div>
<form method="post" action="Request.php?class=app\controller\ItemCtr&method=run">
    <input type="hidden" name="id" id="id" value="<?= $this->model->getId() ?>">
    <div class="row">
        <div class="small-12 medium-6 large-4 columns">
            <label>
                Nome da Categoria:
                <input type="text" name="nome" value="<?= $this->model->getNome() ?>" maxlength="100" required="required">
            </label>
        </div>
        <div class="small-12 medium-3 large-4 columns">
            <label for="valorbase">Valor base:</label>
            <div class="row collapse prefix-radius">
                <div class="small-3 columns">
                    <span class="prefix">R$</span>
                </div>
                <div class="small-9 columns">
                    <input type="number" name="valorbase" id="valorbase" value="<?= $this->model->getValorBase() ?>" id="valorbase" required="required">
                </div>
            </div>
        </div>
        <div class="small-12 medium-3 large-4 columns">
            <label for="categoria">Categoria:</label>
            <div class="row collapse prefix-radius">                
                <div class="small-9 columns">
                    <input type="text" name="categoria" id="categoria" value="<?= $this->model->getCategoria()->getNome() ?>" readonly="" required="required">
                </div>
                <div class="small-3 columns">
                    <a href="#" class="button postfix lupaFundo"></a>
                </div>
            </div>
        </div>
    </div>
    <br/>
    <div class="row">
        <?php
        $medium = "medium-6";
        $large = "large-6";
        if ($this->model->getId() != null && $this->model->getId() != 0) {
            $medium = "medium-4";
            $large = "large-4";
        }
        ?>
        <div class="small-12 <?= $medium ?> <?= $large ?> columns">
            <input type="submit" class="button expand radius success" name="comando" value="Salvar">
        </div>        
        <div class="small-12 <?= $medium ?> <?= $large ?> columns">
            <input type="submit" class="button expand radius info" name="comando" value="Novo">
        </div>
        <?php if ($this->model->getId() != null && $this->model->getId() != 0) { ?>
            <div class="small-12 <?= $medium ?> <?= $large ?> columns">
                <input type="submit" class="button expand radius alert" name="Excluir" value="Excluir">
            </div>
        <?php } ?>
    </div>
    <br/>
    <div class="row">
        <hr/>
    </div>
    <br/>
    <div class="row">
        <div class="small-12 medium-4 large-4 medium-centered large-centered columns">
            <a class="button expand radius secondary" href="Request.php?class=app\controller\ItemCtr&method=showList">Listagem</a>
        </div>
    </div>
    <br>
</form>
