<footer class="row">
    <hr/>
    <div class="small-12 medium-12 large-12 columns">
        <div class="row">
            <div class="large-6 columns">
                <p>&copy; Copyright no one at all. Go to town.</p>
            </div>
        </div>
    </div>
</footer>
<script src="core/vendor/js/jquery.js"></script>
<script src="core/vendor/js/foundation.js"></script>
<script src="core/vendor/js/foundation.topbar.js"></script>
<script src="core/vendor/js/app.js"></script>
<script>
    $(document).foundation();
</script>
</body>
</html>
