<div id="myModal" class="reveal-modal" data-reveal aria-labelledby="modalTitle" aria-hidden="true" role="dialog">
    <h2 id="modalTitle">Resposta da opera&ccedil;&atilde;o!</h2>
    <p class="lead"><?= $this->getMessage(); ?></p>
    <a class="close-reveal-modal" aria-label="Close">&#215;</a>
</div>
<script src="/core/vendor/js/foundation.reveal.js"></script>
<script>
    $(document).foundation();
    $(document).foundation('reveal', 'reflow');
</script>
