<!DOCTYPE html>
<html lang="pt-br">
    <head>
        <meta charset="utf-8">
        <title><?= \core\Application::APP_NAME ?></title>
        <link rel="stylesheet" href="core/vendor/css/foundation.min.css" type="text/css"/>
        <link rel="stylesheet" href="core/vendor/css/normalize.css" type="text/css"/>
        <link rel="stylesheet" href="core/vendor/css/app.css" type="text/css"/>
    </head>
    <body>
        <nav class="top-bar" data-topbar role="navigation">
            <ul class="title-area">
                <li class="name">
                    <h1><a href="#">Planilha Financeira</a></h1>
                </li>
                <li class="toggle-topbar menu-icon"><a href="#"><span>Menu</span></a></li>
            </ul>
            <section class="top-bar-section">
                <!-- Left Nav Section -->
                <ul class="left">
                    <li class="has-dropdown">
                        <a href="#">Cadastros</a>
                        <ul class="dropdown">
                            <li><a href="Request.php?class=app\controller\CategoriaCtr&method=showView">Categoria</a></li>
                            <li><a href="Request.php?class=app\controller\ItemCtr&method=showView">Itens</a></li>
                        </ul>
                    </li>
                    <li class="has-dropdown">
                        <a href="#">Listagens</a>
                        <ul class="dropdown">
                            <li><a href="Request.php?class=app\controller\CategoriaCtr&method=showList">Categoria</a></li>
                            <li><a href="Request.php?class=app\controller\ItemCtr&method=showList">Itens</a></li>
                        </ul>
                    </li>
                    <li class="has-dropdown">
                        <a href="#">Relatórios</a>
                        <ul class="dropdown">
                            <li><a href="Request.php?class=app\controller\RelatorioCtr&method=showViewCategoria">Categoria</a></li>
                            <li><a href="Request.php?class=app\controller\RelatorioCtr&method=showViewItem">Itens</a></li>
                        </ul>
                    </li>
                </ul>
            </section>
        </nav>