<!DOCTYPE html>
<html lang="pt-br">
    <head>
        <meta charset="utf-8">
        <title><?= \core\Application::APP_NAME ?></title>
        <link rel="stylesheet" href="/core/vendor/css/foundation.min.css" type="text/css"/>
        <link rel="stylesheet" href="/core/vendor/css/normalize.css" type="text/css"/>
    </head>
    <body>
        <nav class="top-bar" data-topbar role="navigation">
            <ul class="title-area">
                <li class="name">
                    <h1><a href="#">Planilha Financeira</a></h1>
                </li>
                <li class="toggle-topbar menu-icon"><a href="#"><span>Menu</span></a></li>
            </ul>
            <section class="top-bar-section">
                <!-- Left Nav Section -->
                <ul class="left">
                    <li class="has-dropdown">
                        <a href="#">Controle</a>
                        <ul class="dropdown">
                            <li><a href="#">Item</a></li>
                        </ul>
                    </li>
                </ul>
            </section>
        </nav>